### ISSUE TITLE
QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-aggregator#89]
Received this error message via email from a running Aggregator instance:

> Cannot authenticate client with farmOS server id: 115 - TimeoutError('QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30')QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/3o7r)

The Aggregator frontend is having trouble loading. Some key requests (like `/api/v1/users/me` and `/api/v1/farms`) are not completing, which leads to either a white screen, or an empty farm list.

**Comment by mstenta** [comment]
There weren't any requests being made to the Aggregator when this happened, as far as I know. Though I can dig deeper into the logs to confirm that.

I rebooted the server and now it's working again.

**Comment by mstenta** [comment]
@paul121 committed a potential fix for this: https://github.com/farmOS/farmOS-aggregator/commit/8841202ee7b7003a3b90010acaa13a1e047a2750

Seems to be working well now! I'll continue to monitor the logs and will reopen if we see this again.

**Comment by mstenta** [comment]
Happening again - reopening.

**Comment by paul121** [comment]
With commit b8f7fbee6e759c9f608c6cbb0e12f83ba83f6a27 I've updated so that we are creating DB sessions using a recent feature from FastAPI: [Dependencies with Yield](https://fastapi.tiangolo.com/tutorial/dependencies/dependencies-with-yield/).

This means that sessions are only opened when needed, instead at the beginning of each request as they were with ASGI `middleware`. With `yield` this also means that the sessions are closed *after* an HTTP response has been sent, which might make things a bit faster. In general I'm hoping this will do a better job of cleaning up db sessions.

I'm curious if the background task running the Ping Farms utility was leaving DB sessions open (because the background task was outside the scope of the ASGI `middleware` responsible for closing DB sessions). I've added some logging and can see that it does get closed now. Considering the Ping Farms utility would be running nightly, the timeline lines up for how long it would have taken for the session pool to reach its limit of 10 - but that's just my speculation!

I did come across the following issue that suggests there *might* be issues creating a DB session in a dependency with `yield`:  https://github.com/tiangolo/full-stack-fastapi-postgresq/issues/104 The proposed "solution" of wrapping in another `contextmanager` is confusing though because that is what the FastAPI `yield` dependency does under the hood.. but perhaps there is an issue here.

<hr>

If we are still having issues, I think we should look into the `pool_recycle` parameter (docs [here](https://docs.sqlalchemy.org/en/13/core/engines.html#sqlalchemy.create_engine.params.pool_recycle) which determines how long to wait before closing a connection. It seems like we are only hitting this limit for a small period of time, which suggests the pool opens back up over time. (The Postgres DB should have a default timeout though? Maybe this is too long?)

Increasing our pool size might also avoid this issue, too, although doesn't necessarily fix the problem. Either way, I think this will likely need to be configurable option in the future (if it's not already configurable via environment variables).

**Comment by mstenta** [comment]
Great! Deployed this change. Let's keep an eye on it. Fingers crossed!

**Comment by paul121** [comment]
We saw this happen again and pinned it down to a high number of requests in a short amount of time (1-2 minutes) causing the overflow error. Increasing the SQLAlchemy pool size should fix the problem.

I've made this configurable with the `SQLALCHEMY_POOL_SIZE` and `SQLALCHEMY_MAX_OVERFLOW` environment variables.

Added documentation at [`docs/configuration.md`](https://github.com/farmOS/farmOS-aggregator/blob/master/docs/configuration.md#db-config)
<hr>

Some helpful commands for querying the number of current connections from Postgres:
- `SHOW max_connections;`: Displays the max connections config.
- `SELECT sum(numbackends) FROM pg_stat_database;`: Current number of connections
- `SELECT * FROM pg_stat_activity;`: Detailed info of all current connections


In the dev environment, these can be run with
```
sudo docker-compose exec db psql -h localhost -U postgres
```
